Update to cadvisor 0.47.0
ckotzbauer/helm-charts pull request #133
Opened 2023-01-16 17:59 UTC by roock

This is specially useful as version 0.44.0 doesn't provide any arm64 container image yet. 

Signed-off-by: Roman Pertl <roman@pertl.org>

2023-01-16 18:08 UTC, ckotzbauer requested changes
Thanks! Can you please bump the "version" field from the Chart.yaml?

2023-01-16 18:20 UTC, ckotzbauer commented
> I would also suggest to add the docker type to your dependabot.yml, so future updates will show up automatically. (Updating image tag from helm value files is supported since November 2022).

Thanks for the hint, I prefer renovate over dependabot, I added a config to the repo.

2023-01-17 07:08 UTC, roock commented
> Thanks! Can you please bump the "version" field from the Chart.yaml?

Sure, done!

2023-01-17 07:09 UTC, roock commented
> > I would also suggest to add the docker type to your dependabot.yml, so future updates will show up automatically. (Updating image tag from helm value files is supported since November 2022).
> 
> Thanks for the hint, I prefer renovate over dependabot, I added a config to the repo.

Cool, I prefer renovate too 👍

2023-01-17 07:22 UTC, ckotzbauer approved these changes

2023-01-17 07:22 UTC, merged