Added optional hostPort, hostIP to daemonset. Added optional service creation
ckotzbauer/helm-charts pull request #50
Opened 2021-05-03 23:02 UTC by wesuuu

- Added hostPort & hostIP to daemonset so that each pod could run on the hostIP:port
- Added optional service creation (defaults to create) since it may not be needed if it runs on the hostIP:port

2021-05-04 05:11 UTC, ckotzbauer requested changes
Thanks for your contribution!
Could you please address my comments? I want to avoid a breaking-change for all users which are already using this chart (which then should be a `2.0.0`).
Could you please also add the two fields to the values listing in the README?

2021-05-04 05:11 UTC, ckotzbauer commented on charts/cadvisor/values.yaml
> +  hostPort: 8080
@wesuuu Could you please add the "hostIP" field here as well and comment both that they are not set by default.

2021-05-04 05:11 UTC, ckotzbauer commented on charts/cadvisor/values.yaml
> +  create: false
@wesuuu Please set to `true` to avoid a breaking-change for all existing users of this chart.

2021-05-04 05:11 UTC, ckotzbauer commented on charts/cadvisor/Chart.yaml
> +version: 1.3.2
@wesuuu Could you please change the version to `1.3.0`?

2021-05-05 23:17 UTC, wesuuu commented
Thanks for your feedback, @ckotzbauer. I'll go ahead and make those changes and I'll add an optional hostPorts (https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#hostportrange-v1beta1-policy) within psp.yaml/values.yaml as this was required to get it to work within my psp enabled k8s cluster.

2021-08-10 00:00 UTC, closed without merging